### ISSUE TITLE
Meeting Thu 16.04.2020 - 13:00

### ISSUE THREAD

**Issue by Welko** [Welko/open_iA#4]
**TOPICS**
- [ ] .
- [ ] nicetohaves
- [ ] Warnings

**Comment by Welko** [comment]
Hey @codeling! I decided to open a couple of issues to keep track of what's left to do in this project :)
You're welcome to add/edit anything

What do you say we have a meeting this Thursday 16.04 at 13:00?

**Comment by codeling** [comment]
@Welko yes, this meeting time works for me! Though I find an issue an unusual meeting invitation ;) Closing as ... assigned? agreed? ;)

**Comment by Welko** [comment]
@codeling haha, indeed unusual :)
Wanted to show you these issues; thought it would be a fun way

The idea is to document here what we discuss in the meeting, so I'll keep it open until then

**Comment by codeling** [comment]
Just remember, all the information you put on here is completely public ;)

**Comment by Welko** [comment]
Hmm thanks for the reminder. I didn't have that in mind :)
Then let's leave the meeting talk for other platforms
